# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50f8efc7c348c8e8f9f22e273ef5ac44c37cec6369a07c5527fc8d3aa75086b0cac9cc121d0b960fe76fa9d37f69c5530cf79f7e5e821f2cd92d7df76f45a3e2

test:
  secret_key_base: a1b22cf6094bc3978a1030dcece9002e5ebe9636e6256acb0180d9ae43e241ea188e1398dcbb41f8195db6385621d041a9f75350fb9fad429b966c7a628bf02c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
